version: "3.3"
services:
  postgres:
    image: postgres:12.2
    container_name: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"