CREATE TABLE person (
id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
first_name VARCHAR(255),
last_name VARCHAR(255),
primary key (id));

CREATE TABLE person_event (
id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
first_name VARCHAR(255),
last_name VARCHAR(255),
event varchar(255),
primary key (id));

CREATE TABLE address (
id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
description VARCHAR(255),
person_id int8 not null,
primary key (id));

alter table address add constraint fk_person foreign key (person_id) references person (id);